stages:
  - test
  - JSBuild
  - JSVersionTest
  - clone
  - delete

npm_install:
  stage: test
  image: node:latest
  script:
    - npm install

yarn_install_and_test:
  stage: test
  image: node:latest
  script:
    - yarn install
    - yarn jest

yarn_sync:
  stage: JSBuild
  needs: [yarn_install_and_test]
  script:
    - yarn sync


npm_install_js:
  stage: JSVersionTest
  needs: [yarn_sync]
  script:
    - cd JSVersion
    - npm install

yarn_jest_tests_js:
  stage: JSVersionTest
  needs: [yarn_sync]
  script:
    - cd JSVersion
    - yarn install
    - yarn jest-test

