image: node:latest
stages:
  - test
  - JSBuild
  - JSVersionTest
  - clone
  - delete

npm_install:
  stage: test
  image: node:latest
  script:
    - npm install

yarn_install_and_test:
  stage: test
  image: node:latest
  script:
    - yarn install
    - yarn jest
  artifacts:
    paths:
      - node_modules/
# WHO THE HELL KNOWS WHY I NEED TO RUN YARN SYNC TWICE? IF I DON'T, THE ROOT FOLDER FILES CANNOT BE COPIED? 
# IT IS NOT RELATED TO AWAIT! BECAUSE EVEN IF I USE AWAIT, IT STILL DOESN'T WORK!
yarn_sync:
  stage: JSBuild
  needs: 
    - job: yarn_install_and_test
      artifacts: true
  script:
    - yarn sync
    - yarn sync
  artifacts:
    paths:
      - JSVersion/

npm_install_js:
  stage: JSVersionTest
  needs: 
    - job: yarn_sync
      artifacts: true
  script:
    - cd JSVersion
    - npm install

yarn_jest_tests_js:
  stage: JSVersionTest
  needs: 
    - job: yarn_sync
      artifacts: true
  script:
    - cd JSVersion
    - yarn install
    - yarn jest-test

git_clone:
  stage: clone
  needs: 
    - job: yarn_sync
      artifacts: true
  script:
    - git clone https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/koii-network/dev-blue/k2-task-template-js.git
    - cd k2-task-template-js
    - find . -mindepth 1 ! -regex '^./\.git\(/.*\)?' -delete
    - cd ..
    - cp -r JSVersion/* k2-task-template-js/
    - git add .
    - git commit -m "Update k2-task-template-js version $(cat JSVersion/package.json | grep '"version"' | awk -F'"' '{print $4}')"
    - git push https://oauth2:${GITLAB_ACCESS_TOKEN}@gitlab.com/koii-network/dev-blue/k2-task-template-js.git
  artifacts: 
    paths: 
      - k2-task-template-js/